import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { getUserFromToken } from '@/lib/auth';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = getUserFromToken();


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Image 
          className="dark:invert"
          src="/next.svg"
          alt="Next.js logo"
          width={180}
          height={38}
          style={{margin:"10px"}}
          priority
        />
        <ol style={{marginLeft:"10px"}} className="list-inside list-decimal text-sm/6 text-center sm:text-left font-[family-name:var(--font-geist-mono)]">
        <li className="mb-2 tracking-[-.01em]">
            <Link href="/">Home Page</Link>
          </li>
          {
            !user ?
              <li className="mb-2 tracking-[-.01em]">
                <Link href="/login">Login Page</Link>
              </li> :
              <li className="mb-2 tracking-[-.01em]">
                <Link href="/login">Logout Page</Link>
              </li>
          }
          <li className="mb-2 tracking-[-.01em]">
            <Link href="/dashboard">Dashboard Page</Link>
          </li>
          <li className="mb-2 tracking-[-.01em]">
            <Link href="/users">User Listing Page</Link>
          </li>
          <li className="mb-2 tracking-[-.01em]">
            <Link href="/users/add">Add User Page</Link>
          </li>
        </ol>
        <div style={{margin:"10px"}}>
          {children}
        </div>
      </body>
    </html>
  );
}
